// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIBoard() {
  return window['go']['main']['Game']['GetIBoard']();
}

export function GetUBoard() {
  return window['go']['main']['Game']['GetUBoard']();
}

export function HumanMove(arg1) {
  return window['go']['main']['Game']['HumanMove'](arg1);
}

export function SetShip(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Game']['SetShip'](arg1, arg2, arg3, arg4);
}

export function SummonShips(arg1) {
  return window['go']['main']['Game']['SummonShips'](arg1);
}
