// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIBoard():Promise<Array<number>>;

export function GetUBoard():Promise<Array<number>>;

export function HumanMove(arg1:number):Promise<Array<number>>;

export function SetShip(arg1:number,arg2:number,arg3:number,arg4:boolean):Promise<string>;

export function SummonShips(arg1:number):Promise<void>;
